// let users = [
//   {
//     id_utilizador: 1,
//     email: "admin@email.com",
//     nome: "admin",
//     password: "admin",
//     admin: 1,
//   },
//   {
//     id_utilizador: 2,
//     email: "andres",
//     nome: "andres",
//     password: "4490",
//     admin: 0,
//   },
//   {
//     id_utilizador: 3,
//     email: "fabio",
//     nome: "fabio",
//     password: "fabio",
//     admin: 0,
//   },
//   {
//     id_utilizador: 4,
//     email: "diana",
//     nome: "diana",
//     password: "diana",
//     admin: 0,
//   },
//   {
//     id_utilizador: 5,
//     email: "garyharper@example.com",
//     nome: "John Brown",
//     password: "@938Gc+OF%",
//     admin: 0,
//   },
//   {
//     id_utilizador: 6,
//     email: "justin22@example.org",
//     nome: "Jeffrey Fowler",
//     password: "$XC%OsH0a6",
//     admin: 0,
//   },
//   {
//     id_utilizador: 7,
//     email: "kimberlywilson@example.org",
//     nome: "Derrick Lawrence",
//     password: "$5DiLKicNk",
//     admin: 0,
//   },
//   {
//     id_utilizador: 8,
//     email: "james50@example.net",
//     nome: "Emily Wells",
//     password: "fxhY5fr0(7",
//     admin: 0,
//   },
//   {
//     id_utilizador: 9,
//     email: "acarey@example.com",
//     nome: "Patricia Stanley",
//     password: "5@c8gTDbXT",
//     admin: 0,
//   },
//   {
//     id_utilizador: 10,
//     email: "mary74@example.com",
//     nome: "Katherine Hall",
//     password: "#cNDbGYsW3",
//     admin: 0,
//   },
//   {
//     id_utilizador: 11,
//     email: "dawn15@example.org",
//     nome: "Stephanie Mata",
//     password: "b*v*63Qfqv",
//     admin: 0,
//   },
//   {
//     id_utilizador: 12,
//     email: "swansonpatrick@example.org",
//     nome: "Nichole Warner",
//     password: "+D9DZcdL3r",
//     admin: 0,
//   },
//   {
//     id_utilizador: 13,
//     email: "klinemitchell@example.com",
//     nome: "Edward Oconnor",
//     password: "RFB0Umh6!H",
//     admin: 0,
//   },
//   {
//     id_utilizador: 14,
//     email: "ykelley@example.org",
//     nome: "Anna Morgan",
//     password: "&pQ83Vklne",
//     admin: 0,
//   },
// ];

// Data will go here
// module.exports = users;
