name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install root dependencies
        run: npm install

      - name: Install server dependencies
        run: |
          cd server
          npm install
          cd ..

      - name: Run tests
        run: npm test
